"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-10 17:06:22.812539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('decision_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('require_comment', sa.Boolean(), nullable=False),
    sa.Column('default_next_check_days', sa.Integer(), nullable=True),
    sa.Column('allowed_categories_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('delivery_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('message_thread_id', sa.Integer(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_attempts_entity_id'), 'delivery_attempts', ['entity_id'], unique=False)
    op.create_index(op.f('ix_delivery_attempts_entity_type'), 'delivery_attempts', ['entity_type'], unique=False)
    op.create_table('problem_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('require_comment', sa.Boolean(), nullable=False),
    sa.Column('default_next_check_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_key', sa.String(length=64), nullable=False),
    sa.Column('topic_name', sa.String(length=128), nullable=False),
    sa.Column('message_thread_id', sa.Integer(), nullable=True),
    sa.Column('event_types', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_topic_key'), 'topics', ['topic_key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('private_chat_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('setting_key', sa.String(length=128), nullable=True),
    sa.Column('old_value_json', sa.Text(), nullable=True),
    sa.Column('new_value_json', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('ip_or_source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_log_action'), 'admin_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_actor_user_id'), 'admin_audit_log', ['actor_user_id'], unique=False)
    op.create_table('admin_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_key', sa.String(length=64), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.Column('granted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission_key')
    )
    op.create_index(op.f('ix_admin_permissions_user_id'), 'admin_permissions', ['user_id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article', sa.String(length=32), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('responsible_user_id', sa.Integer(), nullable=True),
    sa.Column('responsible_role', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_article'), 'articles', ['article'], unique=True)
    op.create_table('problem_decision_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_type_id', sa.Integer(), nullable=False),
    sa.Column('decision_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decision_type_id'], ['decision_types.id'], ),
    sa.ForeignKeyConstraint(['problem_type_id'], ['problem_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_type_id', 'decision_type_id')
    )
    op.create_index(op.f('ix_problem_decision_links_problem_type_id'), 'problem_decision_links', ['problem_type_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('validation_rules_json', sa.Text(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_category'), 'system_settings', ['category'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('tasks_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_task_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scenario', sa.String(length=24), nullable=False),
    sa.Column('responsible_user_id', sa.Integer(), nullable=True),
    sa.Column('responsible_role', sa.String(length=32), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('schedule_type', sa.String(length=16), nullable=False),
    sa.Column('schedule_value', sa.String(length=64), nullable=True),
    sa.Column('schedule_interval', sa.Integer(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('due_time', sa.Time(), nullable=True),
    sa.Column('first_run_date', sa.Date(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('run_on_weekends', sa.Boolean(), nullable=False),
    sa.Column('skip_holidays', sa.Boolean(), nullable=False),
    sa.Column('need_approval', sa.Boolean(), nullable=False),
    sa.Column('remind_after_hours', sa.Integer(), nullable=True),
    sa.Column('second_remind_after_hours', sa.Integer(), nullable=True),
    sa.Column('question_receiver_user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_receiver_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_config_external_task_id'), 'tasks_config', ['external_task_id'], unique=True)
    op.create_index(op.f('ix_tasks_config_next_run_at'), 'tasks_config', ['next_run_at'], unique=False)
    op.create_table('task_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('responsible_user_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('schedule_key', sa.String(length=96), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('auto_approved_at', sa.DateTime(), nullable=True),
    sa.Column('postponed_to', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('approval_deadline_at', sa.DateTime(), nullable=True),
    sa.Column('reminders_sent', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('delivery_status', sa.String(length=16), nullable=False),
    sa.Column('delivery_attempts', sa.Integer(), nullable=False),
    sa.Column('last_delivery_error', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('message_sent_at', sa.DateTime(), nullable=True),
    sa.Column('title_snapshot', sa.String(length=255), nullable=False),
    sa.Column('description_snapshot', sa.Text(), nullable=True),
    sa.Column('responsible_name_snapshot', sa.String(length=128), nullable=True),
    sa.Column('need_approval_snapshot', sa.Boolean(), nullable=False),
    sa.Column('approval_timeout_hours_snapshot', sa.Integer(), nullable=False),
    sa.Column('remind_after_hours_snapshot', sa.Integer(), nullable=True),
    sa.Column('second_remind_after_hours_snapshot', sa.Integer(), nullable=True),
    sa.Column('question_receiver_snapshot', sa.Integer(), nullable=True),
    sa.Column('topic_snapshot', sa.Integer(), nullable=True),
    sa.Column('article_batch_size_snapshot', sa.Integer(), nullable=True),
    sa.Column('scenario_snapshot', sa.String(length=24), nullable=False),
    sa.Column('settings_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['tasks_config.id'], ),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'scheduled_at')
    )
    op.create_index(op.f('ix_task_instances_approval_deadline_at'), 'task_instances', ['approval_deadline_at'], unique=False)
    op.create_index(op.f('ix_task_instances_config_id'), 'task_instances', ['config_id'], unique=False)
    op.create_index(op.f('ix_task_instances_next_retry_at'), 'task_instances', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_task_instances_responsible_user_id'), 'task_instances', ['responsible_user_id'], unique=False)
    op.create_index(op.f('ix_task_instances_schedule_key'), 'task_instances', ['schedule_key'], unique=False)
    op.create_index(op.f('ix_task_instances_scheduled_date'), 'task_instances', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_task_instances_status'), 'task_instances', ['status'], unique=False)
    op.create_table('article_check_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_instance_id', sa.Integer(), nullable=False),
    sa.Column('responsible_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_articles', sa.Integer(), nullable=False),
    sa.Column('checked_articles', sa.Integer(), nullable=False),
    sa.Column('action_required_count', sa.Integer(), nullable=False),
    sa.Column('questions_count', sa.Integer(), nullable=False),
    sa.Column('current_batch', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_instance_id')
    )
    op.create_index(op.f('ix_article_check_sessions_status'), 'article_check_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_article_check_sessions_task_instance_id'), 'article_check_sessions', ['task_instance_id'], unique=False)
    op.create_table('task_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_instance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('old_status', sa.String(length=24), nullable=True),
    sa.Column('new_status', sa.String(length=24), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_logs_task_instance_id'), 'task_logs', ['task_instance_id'], unique=False)
    op.create_table('article_check_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_session_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('article_snapshot', sa.String(length=32), nullable=False),
    sa.Column('product_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('check_status', sa.String(length=24), nullable=False),
    sa.Column('checked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['check_session_id'], ['article_check_sessions.id'], ),
    sa.ForeignKeyConstraint(['checked_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('check_session_id', 'article_snapshot')
    )
    op.create_index(op.f('ix_article_check_items_check_session_id'), 'article_check_items', ['check_session_id'], unique=False)
    op.create_index(op.f('ix_article_check_items_check_status'), 'article_check_items', ['check_status'], unique=False)
    op.create_table('article_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_check_item_id', sa.Integer(), nullable=True),
    sa.Column('task_instance_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article', sa.String(length=32), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('problem_type_id', sa.Integer(), nullable=True),
    sa.Column('decision_type_id', sa.Integer(), nullable=True),
    sa.Column('category_name_snapshot', sa.String(length=64), nullable=True),
    sa.Column('problem_name_snapshot', sa.String(length=128), nullable=True),
    sa.Column('decision_name_snapshot', sa.String(length=128), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('next_check_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_check_item_id'], ['article_check_items.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['article_categories.id'], ),
    sa.ForeignKeyConstraint(['decision_type_id'], ['decision_types.id'], ),
    sa.ForeignKeyConstraint(['problem_type_id'], ['problem_types.id'], ),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_actions_article'), 'article_actions', ['article'], unique=False)
    op.create_index(op.f('ix_article_actions_article_check_item_id'), 'article_actions', ['article_check_item_id'], unique=False)
    op.create_index(op.f('ix_article_actions_next_check_date'), 'article_actions', ['next_check_date'], unique=False)
    op.create_index(op.f('ix_article_actions_task_instance_id'), 'article_actions', ['task_instance_id'], unique=False)
    op.create_table('task_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_instance_id', sa.Integer(), nullable=False),
    sa.Column('article_check_item_id', sa.Integer(), nullable=True),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('delivery_status', sa.String(length=16), nullable=False),
    sa.Column('delivery_attempts', sa.Integer(), nullable=False),
    sa.Column('last_delivery_error', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_check_item_id'], ['article_check_items.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instances.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_questions_next_retry_at'), 'task_questions', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_task_questions_status'), 'task_questions', ['status'], unique=False)
    op.create_index(op.f('ix_task_questions_task_instance_id'), 'task_questions', ['task_instance_id'], unique=False)
    op.create_index(op.f('ix_task_questions_to_user_id'), 'task_questions', ['to_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_questions_to_user_id'), table_name='task_questions')
    op.drop_index(op.f('ix_task_questions_task_instance_id'), table_name='task_questions')
    op.drop_index(op.f('ix_task_questions_status'), table_name='task_questions')
    op.drop_index(op.f('ix_task_questions_next_retry_at'), table_name='task_questions')
    op.drop_table('task_questions')
    op.drop_index(op.f('ix_article_actions_task_instance_id'), table_name='article_actions')
    op.drop_index(op.f('ix_article_actions_next_check_date'), table_name='article_actions')
    op.drop_index(op.f('ix_article_actions_article_check_item_id'), table_name='article_actions')
    op.drop_index(op.f('ix_article_actions_article'), table_name='article_actions')
    op.drop_table('article_actions')
    op.drop_index(op.f('ix_article_check_items_check_status'), table_name='article_check_items')
    op.drop_index(op.f('ix_article_check_items_check_session_id'), table_name='article_check_items')
    op.drop_table('article_check_items')
    op.drop_index(op.f('ix_task_logs_task_instance_id'), table_name='task_logs')
    op.drop_table('task_logs')
    op.drop_index(op.f('ix_article_check_sessions_task_instance_id'), table_name='article_check_sessions')
    op.drop_index(op.f('ix_article_check_sessions_status'), table_name='article_check_sessions')
    op.drop_table('article_check_sessions')
    op.drop_index(op.f('ix_task_instances_status'), table_name='task_instances')
    op.drop_index(op.f('ix_task_instances_scheduled_date'), table_name='task_instances')
    op.drop_index(op.f('ix_task_instances_schedule_key'), table_name='task_instances')
    op.drop_index(op.f('ix_task_instances_responsible_user_id'), table_name='task_instances')
    op.drop_index(op.f('ix_task_instances_next_retry_at'), table_name='task_instances')
    op.drop_index(op.f('ix_task_instances_config_id'), table_name='task_instances')
    op.drop_index(op.f('ix_task_instances_approval_deadline_at'), table_name='task_instances')
    op.drop_table('task_instances')
    op.drop_index(op.f('ix_tasks_config_next_run_at'), table_name='tasks_config')
    op.drop_index(op.f('ix_tasks_config_external_task_id'), table_name='tasks_config')
    op.drop_table('tasks_config')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_category'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_problem_decision_links_problem_type_id'), table_name='problem_decision_links')
    op.drop_table('problem_decision_links')
    op.drop_index(op.f('ix_articles_article'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_admin_permissions_user_id'), table_name='admin_permissions')
    op.drop_table('admin_permissions')
    op.drop_index(op.f('ix_admin_audit_log_actor_user_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_action'), table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_topics_topic_key'), table_name='topics')
    op.drop_table('topics')
    op.drop_table('problem_types')
    op.drop_index(op.f('ix_delivery_attempts_entity_type'), table_name='delivery_attempts')
    op.drop_index(op.f('ix_delivery_attempts_entity_id'), table_name='delivery_attempts')
    op.drop_table('delivery_attempts')
    op.drop_table('decision_types')
    op.drop_table('article_categories')
    # ### end Alembic commands ###
